---
    - hosts: all
      become: yes
      become_user: root
      vars_files:
        - vars/ips.yaml
      tasks:
        - name: Accept new ssh fingerprints                                        
          shell: ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts          
          with_items: '{{ modules }}'
        - name: Add CentOS 7 epel release package
          yum:
            name: epel-release
        - name: Install yum prerequisites
          yum:
            name: yum-utils
            state: latest
        - name: Install device-mapper-persistent-data
          yum:
            name: device-mapper-persistent-data
            state: latest
        - name: Install lvm2
          yum:
            name: lvm2
            state: latest
       
        - name: Add Docker repo
          get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
       
        - name: Install Docker
          package:
            name: docker-ce
            state: latest
       
        - name: Start Docker service
          service:
            name: docker
            state: started
            enabled: yes

        - name: Update All package
          yum:
            name: '*'
            state: latest
        - name: Install Git
          yum:
            name: 'git'
            state: latest